

redis:
  host: ""
  port: 00000
  user: "default"
  password: ""


orbits:
  season-1:
    start: "yyyy:MM:dd:HH:mm:ss"
    end: "yyyy:MM:dd:HH:mm:ss"
    tier-amount: 100
    level-multiplier: 100
    tiers:
      0:
        plus:
          description: ""
          icon-sprite: ""
          reward-command: ""
        regular:
          description: ""
          icon-sprite: ""
          reward-command: ""