name: Orbit
version: '${version}'

main: me.stivendarsi.orbit.Orbit
api-version: '26.1.2'
load: POSTWORLD
folia-supported: true
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: true
    MiniPlaceholders:
      required: true
      load: BEFORE
    Nexo:
      required: true
      load: BEFORE
